"use client";
import Link from "next/link";
import { Minus, Plus, Trash2 } from "lucide-react";
import { useCartStore } from "@/stores/cart-store";
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
export function CartPage(){
 const items=useCartStore(s=>s.items),remove=useCartStore(s=>s.removeItem),update=useCartStore(s=>s.updateQuantity),clear=useCartStore(s=>s.clearCart),totals=useCartStore(s=>s.getTotals());
 if(!items.length)return <main className="min-h-screen bg-slate-50 px-6 py-16 text-slate-950"><div className="mx-auto max-w-3xl rounded-3xl border border-slate-200 bg-white p-10 text-center"><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Carrinho</p><h1 className="mt-3 text-3xl font-extrabold">Seu carrinho está vazio</h1><p className="mt-3 text-slate-500">Adicione alguns produtos para continuar.</p><Link href="/produtos" className="mt-7 inline-flex rounded-xl bg-slate-950 px-6 py-3 font-bold text-white">Explorar produtos</Link></div></main>;
 return <main className="min-h-screen bg-slate-50 px-6 py-10 text-slate-950"><div className="mx-auto max-w-6xl"><Link href="/produtos" className="text-sm font-bold text-indigo-600">← Continuar comprando</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Seu pedido</p><h1 className="mt-1 text-3xl font-extrabold">Carrinho</h1></div><button type="button" onClick={clear} className="text-sm font-semibold text-slate-500 hover:text-red-600">Limpar</button></div><div className="mt-8 divide-y divide-slate-200">{items.map(item=><article key={item.productId} className="flex gap-4 py-5 first:pt-0"><div className="grid size-24 shrink-0 place-items-center rounded-2xl bg-indigo-50 font-black text-indigo-200">NV</div><div className="min-w-0 flex-1"><Link href={`/produtos/${item.slug}`} className="font-extrabold hover:text-indigo-600">{item.name}</Link><p className="mt-1 text-sm text-slate-500">{money(item.price)}</p><div className="mt-4 flex items-center justify-between gap-4"><div className="inline-flex items-center rounded-xl border border-slate-200"><button type="button" onClick={()=>update(item.productId,item.quantity-1)} className="grid size-9 place-items-center"><Minus className="size-4"/></button><span className="min-w-10 text-center text-sm font-bold">{item.quantity}</span><button type="button" onClick={()=>update(item.productId,item.quantity+1)} disabled={item.quantity>=item.stock} className="grid size-9 place-items-center disabled:opacity-30"><Plus className="size-4"/></button></div><button type="button" onClick={()=>remove(item.productId)} aria-label={`Remover ${item.name}`} className="text-slate-400 hover:text-red-600"><Trash2 className="size-5"/></button></div></div></article>)}</div></section><aside className="h-fit rounded-3xl border border-slate-200 bg-white p-7"><h2 className="text-xl font-extrabold">Resumo</h2><div className="mt-6 space-y-4 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><strong>{money(totals.subtotal)}</strong></div><div className="flex justify-between"><span className="text-slate-500">Frete</span><strong>{totals.shipping===0?"Grátis":money(totals.shipping)}</strong></div><div className="border-t border-slate-200 pt-4 flex justify-between"><span className="font-bold">Total</span><strong className="text-xl">{money(totals.total)}</strong></div></div><Link href="/checkout" className="mt-7 flex w-full justify-center rounded-xl bg-indigo-600 px-5 py-4 font-bold text-white hover:bg-indigo-700">Ir para checkout</Link><p className="mt-4 text-center text-xs text-slate-400">Preço e estoque serão validados no servidor.</p></aside></div></div></main>;
}
