'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Product={id:string;name:string}; type Image={id:string;product_id:string;path:string;alt:string|null;position:number};
export default function Images(){const [products,setProducts]=useState<Product[]>([]);const [images,setImages]=useState<Image[]>([]);const [id,setId]=useState('');const [msg,setMsg]=useState('');const s=createClient();
  async function load(){const [{data:p},{data:i}]=await Promise.all([s.from('products').select('id,name').order('name'),s.from('product_images').select('id,product_id,path,alt,position').order('position')]);setProducts(p||[]);setImages(i||[])}useEffect(()=>{load()},[]);
  async function upload(file?:File){if(!file||!id)return;setMsg('Enviando...');const ext=file.name.split('.').pop()?.toLowerCase()||'';if(!['jpg','jpeg','png','webp'].includes(ext)){setMsg('Formato não permitido.');return}if(file.size>5*1024*1024){setMsg('Arquivo maior que 5 MB.');return}const path=`${id}/${crypto.randomUUID()}.${ext}`;const {error}=await s.storage.from('product-images').upload(path,file,{contentType:file.type,upsert:false});if(error){setMsg('Upload recusado.');return}const {error:dbError}=await s.from('product_images').insert({product_id:id,path,alt:file.name,position:images.filter(x=>x.product_id===id).length});if(dbError){await s.storage.from('product-images').remove([path]);setMsg('Não foi possível registrar a imagem.');return}setMsg('Imagem enviada.');load()}
  async function remove(image:Image){if(!confirm('Excluir esta imagem?'))return;const {error:storageError}=await s.storage.from('product-images').remove([image.path]);if(storageError){setMsg('Não foi possível remover o arquivo.');return}const {error}=await s.from('product_images').delete().eq('id',image.id);if(error){setMsg('Arquivo removido, mas o registro não pôde ser excluído.');return}load()}
  async function update(image:Image,patch:Partial<Pick<Image,'alt'|'position'>>){const {error}=await s.from('product_images').update(patch).eq('id',image.id);if(error)setMsg('Não foi possível atualizar.');else load()}
  const productName=(pid:string)=>products.find(p=>p.id===pid)?.name||pid;const publicUrl=(path:string)=>s.storage.from('product-images').getPublicUrl(path).data.publicUrl;
  return <main style={{maxWidth:1000,margin:'0 auto',padding:32}}><a href="/admin">← Admin</a><h1>Imagens</h1><section style={{display:'grid',gap:10,maxWidth:650,padding:20,border:'1px solid #ddd',borderRadius:16}}><select value={id} onChange={e=>setId(e.target.value)}><option value="">Selecione o produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="file" accept="image/jpeg,image/png,image/webp" disabled={!id} onChange={e=>upload(e.target.files?.[0])}/><p>JPG, PNG ou WebP · máximo 5 MB</p>{msg&&<p>{msg}</p>}</section><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:16,marginTop:30}}>{images.map(image=><article key={image.id} style={{border:'1px solid #ddd',borderRadius:14,padding:12}}><img src={publicUrl(image.path)} alt={image.alt||''} style={{width:'100%',height:180,objectFit:'cover',borderRadius:10}}/><strong>{productName(image.product_id)}</strong><input value={image.alt||''} aria-label="Texto alternativo" onChange={e=>setImages(images.map(x=>x.id===image.id?{...x,alt:e.target.value}:x))}/><div><button onClick={()=>update(image,{alt:image.alt||null})}>Salvar alt</button><button onClick={()=>remove(image)} style={{marginLeft:8}}>Excluir</button></div></article>)}</div></main>}
