'use client';
import { useMemo, useState } from 'react';

type Product = { id:string; name:string; description:string|null; price:number|string; stock:number; categories?:{name?:string}|{name?:string}[]|null; image?:{path:string;alt:string|null}|null };
const accents=['violet','blue','emerald','amber','rose'];
function categoryName(category:Product['categories']){if(Array.isArray(category))return category[0]?.name??'Geral';return category?.name??'Geral'}
function money(value:number|string){return Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}

export default function Storefront({products}:{products:Product[]}){
  const [query,setQuery]=useState('');const [category,setCategory]=useState('Todos');
  const categories=useMemo(()=>['Todos',...Array.from(new Set(products.map(p=>categoryName(p.categories))))],[products]);
  const filtered=useMemo(()=>products.filter(p=>{const text=`${p.name} ${p.description??''}`.toLowerCase();return text.includes(query.toLowerCase())&&(category==='Todos'||categoryName(p.categories)===category)}),[products,query,category]);
  return <main><div className="announcement">Frete grátis nas compras acima de R$ 199 <span>•</span> Compra segura e protegida</div><header className="site-header"><div className="header-inner"><a className="brand" href="/"><span className="brand-mark">L</span><span>LOJA<span className="brand-dot">.</span></span></a><nav className="desktop-nav"><a href="#produtos">Produtos</a><a href="#beneficios">Por que comprar</a><a href="#ofertas">Ofertas</a></nav><div className="header-actions"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produtos..." aria-label="Buscar produtos"/></label><a className="icon-action" href="/login" aria-label="Minha conta">♙</a><a className="cart-action" href="/carrinho" aria-label="Carrinho">🛒<span>0</span></a></div></div></header>
    <section className="hero" id="ofertas"><div className="hero-copy"><p className="eyebrow">NOVA COLEÇÃO</p><h1>Escolha melhor.<br/><em>Viva melhor.</em></h1><p className="hero-text">Produtos selecionados para transformar sua rotina, com qualidade, preço justo e uma experiência de compra simples.</p><a className="primary-btn" href="#produtos">Explorar produtos <span>→</span></a></div><div className="hero-art"><div className="orb orb-one"/><div className="orb orb-two"/><div className="product-silhouette"><span>✦</span></div><div className="floating-card">QUALIDADE<br/><strong>em cada escolha</strong></div></div></section>
    <section className="benefits" id="beneficios"><div><span>↯</span><div><strong>Entrega rápida</strong><p>Receba sem complicação</p></div></div><div><span>✓</span><div><strong>Compra segura</strong><p>Seus dados sempre protegidos</p></div></div><div><span>↺</span><div><strong>Troca fácil</strong><p>Você compra sem preocupação</p></div></div><div><span>♡</span><div><strong>Atendimento humano</strong><p>Estamos aqui para ajudar</p></div></div></section>
    <section className="catalog" id="produtos"><div className="section-heading"><div><p className="eyebrow">SELEÇÃO DA LOJA</p><h2>Produtos em destaque</h2></div><p className="result-count">{filtered.length} {filtered.length===1?'produto':'produtos'}</p></div><div className="category-row">{categories.map(item=><button key={item} className={category===item?'category active':'category'} onClick={()=>setCategory(item)}>{item}</button>)}</div>{filtered.length===0?<div className="empty-state"><div>⌕</div><h3>Nenhum produto encontrado</h3><p>Tente outra busca ou categoria.</p></div>:<div className="product-grid">{filtered.map((product,index)=>{const out=product.stock<=0;return <article className="product-card" key={product.id}><a href={`/produto/${product.id}`} className={`product-image ${accents[index%accents.length]}`}>{product.image?<img src={`/api/imagem?path=${encodeURIComponent(product.image.path)}`} alt={product.image.alt||product.name} loading="lazy"/>:<div className="abstract-product">{['◈','◇','○','△','✦'][index%5]}</div>}<span className="category-pill">{categoryName(product.categories)}</span>{index<2&&<span className="new-pill">NOVO</span>}</a><div className="product-info"><p className="product-category">{categoryName(product.categories)}</p><a href={`/produto/${product.id}`}><h3>{product.name}</h3></a><p className="product-description">{product.description||'Uma escolha especial para você.'}</p><div className="product-bottom"><div><strong>{money(product.price)}</strong><small>{out?'Esgotado':`${product.stock} disponíveis`}</small></div><a className={out?'buy-btn disabled':'buy-btn'} href={out?undefined:`/produto/${product.id}`} aria-disabled={out}>{out?'Esgotado':'Comprar'}</a></div></div></article>})}</div>}</section>
    <section className="trust-banner"><div><p className="eyebrow">FEITO PARA VOCÊ</p><h2>Menos complicação.<br/><em>Mais satisfação.</em></h2><p>Uma loja pensada para deixar cada etapa da sua compra mais clara, rápida e segura.</p></div><div className="trust-stat"><strong>100%</strong><span>experiência<br/>segura</span></div></section><footer><div className="footer-main"><a className="brand" href="/"><span className="brand-mark">L</span><span>LOJA<span className="brand-dot">.</span></span></a><p>Produtos escolhidos para uma vida melhor.</p><div className="footer-links"><a href="/pedidos">Meus pedidos</a><a href="/login">Minha conta</a><a href="/carrinho">Carrinho</a></div></div><div className="footer-bottom"><span>© 2026 Loja. Todos os direitos reservados.</span><span>Compra segura · Privacidade · Termos</span></div></footer></main>;
}
