import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { deleteProduct } from "@/actions/catalog";
import { updateProductStatus } from "@/actions/admin";
import { AdminActionButton } from "@/components/admin/action-button";
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
export default async function AdminProductsPage(){const session=await auth();if(!session?.user||!["ADMIN","SUPER_ADMIN"].includes(session.user.role))redirect('/admin/login');const products=await prisma.product.findMany({include:{category:true,_count:{select:{orderItems:true}}},orderBy:{createdAt:'desc'}});return <main className="min-h-screen bg-slate-50 px-6 py-10 text-slate-950"><div className="mx-auto max-w-7xl"><div className="flex items-center justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Admin</p><h1 className="mt-1 text-3xl font-extrabold">Produtos</h1></div><Link href="/admin/produtos/novo" className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">Novo produto</Link></div><div className="mt-8 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Produto','Categoria','Preço','Estoque','Status','Ações'].map(h=><th key={h} className="p-4">{h}</th>)}</tr></thead><tbody>{products.map(p=><tr key={p.id} className="border-t border-slate-100"><td className="p-4"><p className="font-bold">{p.name}</p><p className="text-xs text-slate-500">SKU: {p.sku} · {p._count.orderItems} item(ns) vendido(s)</p></td><td className="p-4">{p.category.name}</td><td className="p-4">{money(Number(p.price))}</td><td className={`p-4 font-semibold ${p.stock<5?'text-red-600':''}`}>{p.stock}</td><td className="p-4">{p.isActive?'Ativo':'Inativo'}</td><td className="p-4"><div className="flex items-center gap-2"><Link href={`/admin/produtos/${p.id}/editar`} className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-bold text-white">Editar</Link><AdminActionButton label={p.isActive?'Desativar':'Ativar'} action={()=>updateProductStatus(p.id,!p.isActive)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-bold"/></div></td></tr>)}</tbody></table>{products.length===0&&<p className="p-8 text-center text-slate-500">Nenhum produto cadastrado.</p>}</div></div></main>}
