'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Product = { id:string; name:string; slug:string; description:string|null; price:number; stock:number; active:boolean; category_id:string|null };
type Category = { id:string; name:string; slug:string };
const blank = { name:'', slug:'', description:'', price:'', stock:'', category_id:'' };

export default function ProductsAdmin() {
  const [items,setItems] = useState<Product[]>([]); const [cats,setCats] = useState<Category[]>([]);
  const [form,setForm] = useState(blank); const [editing,setEditing] = useState<string|null>(null); const [msg,setMsg] = useState('');
  const supabase = createClient();
  async function load(){const [{data:p},{data:c}]=await Promise.all([supabase.from('products').select('*').order('created_at',{ascending:false}),supabase.from('categories').select('*').order('name')]);setItems(p||[]);setCats(c||[])}
  useEffect(()=>{load()},[]);
  function startEdit(p:Product){setEditing(p.id);setForm({name:p.name,slug:p.slug,description:p.description||'',price:String(p.price),stock:String(p.stock),category_id:p.category_id||''});setMsg('')}
  function reset(){setEditing(null);setForm(blank)}
  async function save(){const price=Number(form.price),stock=Number(form.stock);if(!form.name.trim()||!form.slug.trim()||!Number.isFinite(price)||price<0||!Number.isInteger(stock)||stock<0){setMsg('Preencha os dados corretamente.');return}const payload={name:form.name.trim(),slug:form.slug.trim(),description:form.description.trim()||null,price,stock,category_id:form.category_id||null};const result=editing?await supabase.from('products').update(payload).eq('id',editing).select().single():await supabase.from('products').insert(payload).select().single();if(result.error){setMsg('Não foi possível salvar. Verifique slug duplicado e permissões.');return}setMsg(editing?'Produto atualizado.':'Produto criado.');reset();await load()}
  async function toggle(p:Product){const {error}=await supabase.from('products').update({active:!p.active}).eq('id',p.id);if(error)setMsg('Não foi possível alterar o status.');else await load()}
  async function remove(p:Product){if(!confirm(`Excluir ${p.name}?`))return;const {error}=await supabase.from('products').delete().eq('id',p.id);if(error)setMsg('Não foi possível excluir. Remova imagens/relacionamentos antes.');else await load()}
  return <main style={{maxWidth:1100,margin:'0 auto',padding:32}}><a href="/admin">← Admin</a><h1>Produtos</h1><section style={{display:'grid',gap:10,maxWidth:650,padding:20,border:'1px solid #ddd',borderRadius:16}}><h2>{editing?'Editar produto':'Novo produto'}</h2><input placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><textarea placeholder="Descrição" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Preço" type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="Estoque" type="number" min="0" step="1" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Sem categoria</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div><button onClick={save}>{editing?'Salvar alterações':'Criar produto'}</button>{editing&&<button onClick={reset} style={{marginLeft:8}}>Cancelar</button>}</div>{msg&&<p>{msg}</p>}</section><div style={{overflowX:'auto',marginTop:30}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th>Produto</th><th>Preço</th><th>Estoque</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map(p=><tr key={p.id} style={{borderTop:'1px solid #ddd'}}><td>{p.name}</td><td>R$ {Number(p.price).toFixed(2).replace('.',',')}</td><td>{p.stock}</td><td>{p.active?'Ativo':'Inativo'}</td><td><button onClick={()=>startEdit(p)}>Editar</button> <button onClick={()=>toggle(p)}>{p.active?'Desativar':'Ativar'}</button> <button onClick={()=>remove(p)}>Excluir</button></td></tr>)}</tbody></table></div></main>;
}
