import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
const statusLabels: Record<string, string> = { PENDING: "Aguardando pagamento", PAID: "Pago", PROCESSING: "Em preparação", SHIPPED: "Enviado", DELIVERED: "Entregue", CANCELLED: "Cancelado" };
const paymentLabels: Record<string, string> = { PIX: "PIX", CARD: "Cartão", BOLETO: "Boleto" };

export default async function OrderDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session?.user?.id) redirect("/login");
  const { id } = await params;
  const order = await prisma.order.findFirst({ where: { id, userId: session.user.id }, include: { items: true, address: true } });
  if (!order) notFound();
  return <main className="min-h-screen bg-slate-50 px-6 py-10 text-slate-950"><div className="mx-auto max-w-5xl"><Link href="/conta/pedidos" className="text-sm font-bold text-indigo-600">← Meus pedidos</Link><div className="mt-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Detalhes do pedido</p><h1 className="mt-2 text-3xl font-extrabold">#{order.id.slice(-8).toUpperCase()}</h1><p className="mt-2 text-sm text-slate-500">Realizado em {order.createdAt.toLocaleString("pt-BR")}</p></div><div className="rounded-xl bg-indigo-50 px-4 py-3 text-sm font-bold text-indigo-700">{statusLabels[order.status]}</div></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_340px]"><section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-xl font-extrabold">Produtos</h2><div className="mt-5 divide-y divide-slate-200">{order.items.map(item => <div key={item.id} className="flex justify-between gap-5 py-5 first:pt-0"><div><p className="font-bold">{item.productName}</p><p className="mt-1 text-sm text-slate-500">{item.quantity} × {money(Number(item.price))}</p></div><strong>{money(Number(item.subtotal))}</strong></div>)}</div></section><aside className="space-y-6"><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-extrabold">Resumo</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Subtotal</dt><dd>{money(Number(order.subtotal))}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Frete</dt><dd>{Number(order.shipping) === 0 ? "Grátis" : money(Number(order.shipping))}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Desconto</dt><dd>{money(Number(order.discount))}</dd></div><div className="flex justify-between border-t border-slate-200 pt-4 text-base"><dt className="font-bold">Total</dt><dd className="font-black">{money(Number(order.total))}</dd></div></dl><p className="mt-4 text-xs text-slate-500">Pagamento: {paymentLabels[order.paymentMethod]} · {order.paymentStatus === "APPROVED" ? "Aprovado" : order.paymentStatus === "FAILED" ? "Falhou" : order.paymentStatus === "REFUNDED" ? "Estornado" : "Pendente"}</p></section><section className="rounded-3xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-extrabold">Entrega</h2><address className="mt-4 not-italic text-sm leading-6 text-slate-600">{order.address.recipient}<br />{order.address.street}, {order.address.number}{order.address.complement ? `, ${order.address.complement}` : ""}<br />{order.address.neighborhood}<br />{order.address.city} - {order.address.state}<br />CEP {order.address.zipCode}</address></section></aside></div></div></main>;
}
