"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";

const productSchema = z.object({
  id: z.string().cuid(), categoryId: z.string().cuid(), name: z.string().trim().min(2).max(160),
  slug: z.string().trim().min(2).max(160).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  description: z.string().trim().min(10).max(5000), sku: z.string().trim().min(2).max(60).regex(/^[A-Za-z0-9_-]+$/),
  price: z.coerce.number().positive().max(99999999.99), comparePrice: z.coerce.number().positive().max(99999999.99).nullable().optional(),
  stock: z.coerce.number().int().min(0).max(1000000), isFeatured: z.boolean(), isActive: z.boolean(),
});
const categorySchema = z.object({id:z.string().cuid(),name:z.string().trim().min(2).max(80),slug:z.string().trim().min(2).max(80).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),description:z.string().trim().max(500).nullable().optional(),isActive:z.boolean()});
async function admin(){const s=await auth();if(!s?.user||!['ADMIN','SUPER_ADMIN'].includes(s.user.role))throw new Error('Acesso administrativo negado.');return s.user;}
export async function updateProduct(input:unknown){await admin();const p=productSchema.safeParse(input);if(!p.success)return{success:false,message:'Revise os dados do produto.'};try{await prisma.product.update({where:{id:p.data.id},data:{categoryId:p.data.categoryId,name:p.data.name,slug:p.data.slug,description:p.data.description,sku:p.data.sku,price:p.data.price,comparePrice:p.data.comparePrice??null,stock:p.data.stock,isFeatured:p.data.isFeatured,isActive:p.data.isActive}});revalidatePath('/produtos');revalidatePath('/admin/produtos');return{success:true};}catch{return{success:false,message:'Não foi possível atualizar. SKU, slug ou categoria podem ser inválidos.'};}}
export async function updateProductStatus(id:string,isActive:boolean){await admin();if(!z.string().cuid().safeParse(id).success)return{success:false,message:'Produto inválido.'};await prisma.product.update({where:{id},data:{isActive:Boolean(isActive)}});revalidatePath('/produtos');revalidatePath('/admin/produtos');return{success:true};}
export async function updateProductStock(id:string,stock:unknown){await admin();const parsed=z.object({id:z.string().cuid(),stock:z.coerce.number().int().min(0).max(1000000)}).safeParse({id,stock});if(!parsed.success)return{success:false,message:'Estoque inválido.'};await prisma.product.update({where:{id},data:{stock:parsed.data.stock}});revalidatePath('/produtos');revalidatePath('/admin/produtos');return{success:true};}
export async function updateCategory(input:unknown){await admin();const p=categorySchema.safeParse(input);if(!p.success)return{success:false,message:'Dados da categoria inválidos.'};try{await prisma.category.update({where:{id:p.data.id},data:{name:p.data.name,slug:p.data.slug,description:p.data.description??null,isActive:p.data.isActive}});revalidatePath('/produtos');revalidatePath('/admin/categorias');return{success:true};}catch{return{success:false,message:'Não foi possível atualizar a categoria.'};}}
export async function updateOrderStatus(id:string,status:unknown){await admin();const p=z.object({id:z.string().cuid(),status:z.enum(['PENDING','PAID','PROCESSING','SHIPPED','DELIVERED','CANCELLED'])}).safeParse({id,status});if(!p.success)return{success:false,message:'Status inválido.'};await prisma.order.update({where:{id:p.data.id},data:{status:p.data.status}});revalidatePath('/admin/pedidos');revalidatePath(`/admin/pedidos/${id}`);revalidatePath(`/conta/pedidos/${id}`);return{success:true};}
export async function updatePaymentStatus(id:string,paymentStatus:unknown){await admin();const p=z.object({id:z.string().cuid(),paymentStatus:z.enum(['PENDING','APPROVED','FAILED','REFUNDED'])}).safeParse({id,paymentStatus});if(!p.success)return{success:false,message:'Status de pagamento inválido.'};await prisma.order.update({where:{id:p.data.id},data:{paymentStatus:p.data.paymentStatus}});revalidatePath('/admin/pedidos');revalidatePath(`/admin/pedidos/${id}`);revalidatePath(`/conta/pedidos/${id}`);return{success:true};}
export async function updateUserAccess(id:string,isBlocked:boolean){const me=await admin();if(!z.string().cuid().safeParse(id).success)return{success:false,message:'Usuário inválido.'};if(id===me.id)return{success:false,message:'Você não pode bloquear sua própria conta.'};const target=await prisma.user.findUnique({where:{id},select:{role:true}});if(!target)return{success:false,message:'Usuário não encontrado.'};if(target.role==='SUPER_ADMIN')return{success:false,message:'A conta SUPER_ADMIN não pode ser bloqueada por este painel.'};await prisma.user.update({where:{id},data:{isBlocked:Boolean(isBlocked)}});revalidatePath('/admin/usuarios');return{success:true};}
export async function updateUserRole(id:string,role:unknown){const me=await admin();const p=z.object({id:z.string().cuid(),role:z.enum(['CUSTOMER','ADMIN'])}).safeParse({id,role});if(!p.success)return{success:false,message:'Função inválida.'};if(id===me.id)return{success:false,message:'Você não pode alterar sua própria função.'};if(me.role!=='SUPER_ADMIN')return{success:false,message:'Somente SUPER_ADMIN pode alterar funções.'};const target=await prisma.user.findUnique({where:{id},select:{role:true}});if(!target)return{success:false,message:'Usuário não encontrado.'};if(target.role==='SUPER_ADMIN')return{success:false,message:'SUPER_ADMIN é protegido.'};await prisma.user.update({where:{id},data:{role:p.data.role}});revalidatePath('/admin/usuarios');return{success:true};}
